apiVersion: 1

datasources:
  - name: PostgreSQL - Ingestion Schema
    type: postgres
    access: proxy
    url: ${DB_HOST}:5432
    database: ${DB_NAME}
    user: ${ANALYTICS_DB_USER}
    secureJsonData:
      password: ${ANALYTICS_DB_PASSWORD}
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1400
      timescaledb: false
      database: ${DB_NAME}
    isDefault: true
    editable: false


